name: HRR Intake
description: Upload HRR raw CSV(s) and provide rows for the database.csv
title: "HRR Intake: <short topic or ID>"
labels: ["hrr-intake"]
body:
  - type: markdown
    attributes:
      value: |
        **Instructions**
        1) Attach raw CSV file(s) by drag-and-drop below (GitHub will insert links).
        2) For each attachment, fill out the following block (IDs can simply be 1, 2, 3... **for this issue only**—we handle the global IDs in the CSV):

           ```
           ID: <per-issue number>
           Scource in IDEEE: <who provided the data>
           Topic: <topic name>
           Filename (save as): <desired filename in database.csv>
           Time Unit: <e.g., s>
           Energy Unit: <e.g., kW>
           Attachment filename: <the name GitHub inserts after you upload the file>
           ```

        3) Repeat the block for every file you are submitting and paste the combined text into the field below.

  - type: textarea
    id: rows_csv
    attributes:
      label: File details for database.csv
      description: Copy/paste one block per file using the template from the instructions.
      value: |
        ID: 1
        Scource in IDEEE: Siemens Switzerland AG; DBI
        Topic: car
        Filename (save as): CAR_2010_Test01_raw.csv
        Time Unit: s
        Energy Unit: kW
        Attachment filename: CAR_2010_Test01_raw.csv (uploaded below)

        ID: 2
        Scource in IDEEE: Siemens Switzerland AG; DBI
        Topic: car
        Filename (save as): CAR_2010_Test02_raw.csv
        Time Unit: s
        Energy Unit: kW
        Attachment filename: CAR_2010_Test02_raw.csv (uploaded below)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Anything the maintainers should know.
